### PR TITLE
Removed off by one error

### PR DESCRIPTION
**Pull request by ACK-J**
- I'm not sure if the +1 is supposed to be there but I don't believe it is
#26

### CODE REVIEW

**Comment by ACK-J** [comment]
Also I'm not sure but does line `604` have to replace `i` to be `j`?
https://github.com/moneroexamples/transactions-export/blob/2293411d2cd046c340ae6daabf46faede06072b2/main.cpp#L604-L609

**Comment by moneroexamples** [comment]
It depends if its better to start counting positions from 0 or 1? Currently it counts from 1, thus `+ 1`. Which way is better in your view?

**Comment by ACK-J** [comment]
Upon making these changes all `Ring_no` are set to `0` after exporting many wallets. I'm not sure if this is a bug or if they all actually are the first signature in the ring. Sorry for all the bug fixes and comments, I appreciate your work and just need to make sure the export works as it is crucial to my research.
```
Timestamp,Block_no,Tx_hash,Output_pub_key,Key_image,Ring_no/Ring_size
2022-02-19 18:06:45,1921688,f37126b0dc81f0be8875daccfa660e2851a59bce329352b884e4f6d82c413ab2,f7d5a5d89ea6b302ae7e2488054a2c240c99682f4fefee98f39c66a5b4018d6d,f33209e4991c215968d6b15bc4251f5b53bb61fe78262335dcc8c141c8df9266,0/11
2022-02-20 06:09:49,1922034,685f6ab261289ee1aedbb2967a34d88e2c110474eaa05cd661b3eaf0b5e04486,8ec468c6e576619165b100c05a2ef77f8fadd7c4fffe9ff0c7f7d5eb7985018b,192a42b187d7d86f12a8972ea0113129ca82b845a6db8b0714f1f88a10ae4d88,0/11
2022-02-20 18:07:02,1922383,c271867ae263443b82dddb44f238d30e9aca1b9e0ea511fd46d03911ae923301,ef07638f6f96bb6112a7c0a99e2867df0386a7c6b6c82bf6e3c0c004f9eafa9e,f6bb6bff3e4459b205999117c3456681aec8bcfe4eea04b6b426256dc7b2cf0c,0/11
2022-02-20 18:07:02,1922383,c271867ae263443b82dddb44f238d30e9aca1b9e0ea511fd46d03911ae923301,5dec39d98c11fc349fea9c782a4c695539a9a62809cf8e2fa7dcc0539fa93e6d,9215de86aef5ffa413bea354f1f857f2b45001e16bd5651760ab033af043c09f,0/11
2022-02-21 06:07:05,1922749,2e7648669369e984c0d13a5135b7d35069c714b2b05d3dc1e7af05166dd341f2,e7aae0790068768194b835fc383285198fded7928233c4a72e54d6b5bb568147,e7bfb9e2981e18940e5e6bd78c92cb184b2a0361d80ed1006fb9fd5135189587,0/11
2022-02-21 06:07:05,1922749,2e7648669369e984c0d13a5135b7d35069c714b2b05d3dc1e7af05166dd341f2,66171cacc060607350c3a8628e05f96b2bf5195f6da62f1c53ec56c86ebad7c5,9c16bd54560ddc64963ea16a4a9e875801d064c2f26284d6deda8b899ce22b1a,0/11
2022-02-21 18:06:28,1923081,498af5b1444a91be7e718e527c9940a3f957eb6810dc548546596f4e66c4b17c,4394c4f5e738fa4aa05985d50cece428d82bd7ac1e0cf5f3e143ddf0346a93b6,aa9926d70981a5fd3f69b7b10baad4001a367c59ca26fe8f230f408fc73444f3,0/11
2022-02-21 18:06:28,1923081,498af5b1444a91be7e718e527c9940a3f957eb6810dc548546596f4e66c4b17c,68d8ce82e30195f73e7a2800b11305f6162618e57b9e0951c8454a43418c46f3,8921a39ddeea946611dff2d130b79436e9187bea910d17c48077efcfafea1392,0/11
2022-02-21 21:03:45,1923163,36feff506954dc33393b60852c0c144322cbd8fe0b6ac4a92386d115a141df8c,9fdfe90acc7174944e68abe11de91fd9bdea86544a491553a956f8f1e9e871d9,e197e6e7eebf26a0cc54f16ddaa8d82a36df1638d856bdd5915c411f056b42b8,0/11
2022-02-21 21:03:45,1923163,36feff506954dc33393b60852c0c144322cbd8fe0b6ac4a92386d115a141df8c,e1edb88fe9ff48deecfdc7443febf4e193074d6b350a01d9947ed3233972fda9,d0c00622d2b9a43bf1e0ea9fcb072f15d2b5b605b4085d112b8e8c8425f51dc4,0/11
2022-02-22 15:56:26,1923774,afa7374e00816af398d40530430243bcff78da1c7fa5d25122aed57c61e69fcd,83cc4fb83a0f9bc8ef25c945ed9b434435b7f38203fd5c6cfaa0854bf6b2a437,e7ce336384c76caa1f50e9e93e8c595a81c3ce594dfa85d7bc88b41b79ccaa5c,0/11
2022-02-22 15:56:26,1923774,afa7374e00816af398d40530430243bcff78da1c7fa5d25122aed57c61e69fcd,8da18d65db7af8725fd9ce78091febc98cc3c9a6950757d74433567badfd581d,5015a9407d25671aa9b31a6dd0a5c97648e7bb25553642168dadfb0ecb13e228,0/11
2022-02-22 17:35:10,1923822,cfc1ba1c70e2289c244b96656187f9d179beb1c5c73d968ad2aaf7df81f9b81e,a98663c6b27129260c3a2c68089053f294bd07ff24146ae83642ea9febefda8f,90882aa794aca883db38148d43adbbaf6234ce980ad9c972037b6fcbb0c0845a,0/11
2022-02-22 17:35:10,1923822,cfc1ba1c70e2289c244b96656187f9d179beb1c5c73d968ad2aaf7df81f9b81e,80f656ab3583f645b93eed7966866c3970c6bd825bb5b05e87ac1dffb2903e5e,654307df90a186ec73cf4cdcce2bd32a73d95742c63490cbc7bbfab3f4528025,0/11
2022-02-23 05:52:21,1924184,5ec3b4e4fe4b86adf59d6a106368cd4518aae6b5167d834ebdf49dd65681cc95,7d34cdff4ccac2c3b28c00d839da4540acd59f8d208fb4bbb3e0f5c928b6b0e3,e0ab455aaf1ed2747b4d669c2e735fc52b6ecc12fbee6148e3c11bccf35c8834,0/11
2022-02-23 05:52:21,1924184,5ec3b4e4fe4b86adf59d6a106368cd4518aae6b5167d834ebdf49dd65681cc95,07f6f1cf73224ac8d01440ec211d8dbdca35f295c14883f07b59507dd3f20012,681714a5122741a53ed52ad962ce11126a578eb5b52e4227837a7ec5740a0a74,0/11
2022-02-23 17:54:56,1924528,a7106632b8f2391309637be9ab41d45ef678bce916fb32643222f0141353c1b7,1ef17078f78b8db273cffaeb00f38aa9b210612693069d033dc7284ebb28b071,ab07cc16b3b820dc44eebce8aefced241fcf6484bb1b48b1805b8e4aba70e46b,0/11
2022-02-23 17:54:56,1924528,a7106632b8f2391309637be9ab41d45ef678bce916fb32643222f0141353c1b7,9c40090184ac5e250c1aed6f673e8fddd456cb8facddd67ca059fb5dfb9077ce,7e3c4f1ce178af07e2a6a99f0e8157036fb1e48b35e6d3b400e57dc741e663e7,0/11
2022-02-23 20:51:24,1924631,a423228edc64b5432e43db282b03752cdb2a6e9cff97c9e6008e206c48daa1eb,a55bbc6b2dd6f2ceb64c1469a8baccf77fe9eae0f5a1acfdbdddf4482d8b5e48,8cd9d8ab11202e4a71d8c3ba7bd5f276040337336a3ea76a87c4149556f7049f,0/11
2022-02-23 20:51:24,1924631,a423228edc64b5432e43db282b03752cdb2a6e9cff97c9e6008e206c48daa1eb,8e23da738deebca3d990d81fddaa06d4575e3538896d5740c13b2a9d4a4fd620,1d0edaa95ef5200a75514026a39c4623eed41d0cf41206fe1521876777b94099,0/11
```

**Comment by ACK-J** [comment]
> It depends if its better to start counting positions from 0 or 1? Currently it counts from 1, thus `+ 1`. Which way is better in your view?

Yea that makes a lot more sense to start at 1. Don't know why I didn't think of that.

**Comment by moneroexamples** [comment]
I think so, as output at last position will be 11/11, rather then 10/11.

**Comment by ACK-J** [comment]
I agree!

**Pull request closed without merging**
